---
title: "ggBoxes: Two Dimensional Box and Error Plots"
output:
  github_document:
    html_preview: false
editor_options:
  chunk_output_type: console
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-"
)
```


To install the development version of the package, use the `remotes` package:

```{r, eval=FALSE}
remotes::install_github('jbryer/ggBoxes')
```

## Two Dimensional Box and Whisker Plots

Basic example using the `mtcars` dataset.

```{r boxplot2d_mtcars, message=FALSE, warning=FALSE, error=FALSE}
library(ggBoxes)
data(mtcars)
ggplot(mtcars, aes(x = wt, y = mpg, group = factor(cyl),
				   color = factor(cyl), fill = factor(cyl))) +
	geom_boxplot2d() +
	theme(legend.position = 'bottom') +
	ggtitle('Two Dimensional Box Plot')
```


## Two Dimensional Confidence Intervals (Error Boxes)

```{r error2d_mtcars, message=FALSE, warning=FALSE, error=FALSE}
p <- ggplot(mtcars, aes(x = wt, y = mpg, group = factor(cyl),
				   color = factor(cyl), fill = factor(cyl))) +
	geom_errorbox2d() +
	theme(legend.position = 'bottom') +
	ggtitle('Two Dimensional Confidence Interval Plot', 
			subtitle = 'p = 0.10, p = 0.05, and p = 0.01')
ggExtra::ggMarginal(p + geom_point(alpha = 0), 
					type = 'density', 
					groupColour = TRUE, 
					groupFill = TRUE)
```


